package main

import (
	"log"
	"net"
	"os"

	"github.com/joho/godotenv"
	"github.com/yourname/payment-system/payment-service/db"
	"github.com/yourname/payment-system/payment-service/handler"
	pb "github.com/yourname/payment-system/payment-service/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection" // allows tools like grpcurl to inspect your service
)

func main() {
	_ = godotenv.Load()

	// Connect to PostgreSQL
	db.Connect()

	// Determine which port to run on
	port := os.Getenv("GRPC_PORT")
	if port == "" {
		port = "9090"
	}

	// Create a TCP listener
	lis, err := net.Listen("tcp", ":"+port)
	if err != nil {
		log.Fatalf("❌ Failed to listen: %v", err)
	}

	// Create the gRPC server with logging interceptor
	grpcServer := grpc.NewServer(
		grpc.UnaryInterceptor(loggingInterceptor),
	)

	// Register our PaymentService implementation
	pb.RegisterPaymentServiceServer(grpcServer, &handler.Server{})

	// Enable reflection so you can test with grpcurl without proto files
	reflection.Register(grpcServer)

	log.Printf("🚀 Payment Service (gRPC) listening on :%s", port)
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("❌ gRPC server failed: %v", err)
	}
}

// RegisterPaymentServiceServer is what would be generated by protoc.
// We define it here manually since we're not running protoc in this example.
func init() {
	// This wires up the proto registration.
	// In a real project, protoc generates this automatically.
}
