package main

import (
	"context"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"

	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/sumitDon47/payment-system/payment-service/db"
	"github.com/sumitDon47/payment-system/payment-service/handler"
	"github.com/sumitDon47/payment-system/payment-service/middleware"
	model "github.com/sumitDon47/payment-system/payment-service/models"
	"github.com/sumitDon47/payment-system/payment-service/outbox"
	pb "github.com/sumitDon47/payment-system/payment-service/proto"
	"github.com/sumitDon47/payment-system/payment-service/utils"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

func main() {
	_ = godotenv.Load()

	// Log startup
	utils.Info("Payment Service starting", map[string]interface{}{
		"service":     "payment-service",
		"environment": os.Getenv("ENVIRONMENT"),
	})

	// Connect to PostgreSQL
	db.Connect()
	utils.Info("Database connected", map[string]interface{}{})

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Determine which port to run on
	port := getEnv("PAYMENT_SERVICE_GRPC_PORT", "9090")
	kafkaBroker := getEnv("KAFKA_BROKER", "localhost:29092")
	kafkaTopic := getEnv("KAFKA_TOPIC", model.TopicPaymentCompleted)
	dlqTopic := getEnv("KAFKA_DLQ_TOPIC", model.TopicPaymentDLQ)
	maxRetries := getEnvAsInt("OUTBOX_MAX_RETRIES", 5)

	// Create a TCP listener
	lis, err := net.Listen("tcp", ":"+port)
	if err != nil {
		utils.Error("Failed to listen on port", err, map[string]interface{}{
			"port": port,
		})
		os.Exit(1)
	}

	// Start a separate HTTP server for Prometheus metrics
	go func() {
		http.Handle("/metrics", promhttp.Handler())
		utils.Info("Prometheus metrics server started", map[string]interface{}{
			"port": "8081",
			"path": "/metrics",
		})
		if err := http.ListenAndServe(":8081", nil); err != nil && err != http.ErrServerClosed {
			utils.Error("Failed to start metrics server", err, map[string]interface{}{})
		}
	}()

	// Create the gRPC server with logging and rate limiting interceptors
	rateLimiterInterceptor := middleware.NewRateLimiterInterceptor()
	grpcServer := grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			loggingInterceptor,
			middleware.UnaryServerInterceptor(rateLimiterInterceptor),
		),
	)

	// Register our PaymentService implementation
	pb.RegisterPaymentServiceServer(grpcServer, &handler.Server{})

	if strings.EqualFold(getEnv("ENABLE_GRPC_REFLECTION", "false"), "true") {
		reflection.Register(grpcServer)
		utils.Info("gRPC reflection enabled", map[string]interface{}{})
	}

	// Start the outbox dispatcher to publish pending events to Kafka.
	dispatcher := outbox.NewDispatcher(db.DB, kafkaBroker, kafkaTopic, dlqTopic, maxRetries)
	go dispatcher.Start(ctx)
	utils.Info("Outbox dispatcher started", map[string]interface{}{
		"kafka_broker": kafkaBroker,
		"max_retries":  maxRetries,
	})

	go func() {
		<-ctx.Done()
		utils.Info("Shutdown signal received", map[string]interface{}{})
		grpcServer.GracefulStop()
	}()

	utils.Info("Payment Service listening", map[string]interface{}{
		"port":     port,
		"protocol": "gRPC",
	})
	if err := grpcServer.Serve(lis); err != nil {
		if ctx.Err() == nil {
			utils.Error("gRPC server failed", err, map[string]interface{}{})
			os.Exit(1)
		}
		utils.Info("Payment service stopped", map[string]interface{}{})
	}
}

func getEnv(key, defaultVal string) string {
	if val := os.Getenv(key); val != "" {
		return val
	}
	return defaultVal
}

func getEnvAsInt(key string, defaultVal int) int {
	val := os.Getenv(key)
	if val == "" {
		return defaultVal
	}

	parsed, err := strconv.Atoi(val)
	if err != nil || parsed <= 0 {
		return defaultVal
	}

	return parsed
}

// RegisterPaymentServiceServer is what would be generated by protoc.
// We define it here manually since we're not running protoc in this example.
func init() {
	// This wires up the proto registration.
	// In a real project, protoc generates this automatically.
}
