package main

import (
	"context"
	"log"
	"net"
	"os"
	"os/signal"
	"strconv"
	"syscall"

	"github.com/joho/godotenv"
	"github.com/sumitDon47/payment-system/payment-service/db"
	"github.com/sumitDon47/payment-system/payment-service/handler"
	model "github.com/sumitDon47/payment-system/payment-service/models"
	"github.com/sumitDon47/payment-system/payment-service/outbox"
	pb "github.com/sumitDon47/payment-system/payment-service/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection" // allows tools like grpcurl to inspect your service
)

func main() {
	_ = godotenv.Load()

	// Connect to PostgreSQL
	db.Connect()

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Determine which port to run on
	port := getEnv("GRPC_PORT", "9090")
	kafkaBroker := getEnv("KAFKA_BROKER", "localhost:29092")
	kafkaTopic := getEnv("KAFKA_TOPIC", model.TopicPaymentCompleted)
	dlqTopic := getEnv("KAFKA_DLQ_TOPIC", model.TopicPaymentDLQ)
	maxRetries := getEnvAsInt("OUTBOX_MAX_RETRIES", 5)

	// Create a TCP listener
	lis, err := net.Listen("tcp", ":"+port)
	if err != nil {
		log.Fatalf("❌ Failed to listen: %v", err)
	}

	// Create the gRPC server with logging interceptor
	grpcServer := grpc.NewServer(
		grpc.UnaryInterceptor(loggingInterceptor),
	)

	// Register our PaymentService implementation
	pb.RegisterPaymentServiceServer(grpcServer, &handler.Server{})

	// Enable reflection so you can test with grpcurl without proto files
	reflection.Register(grpcServer)

	// Start the outbox dispatcher to publish pending events to Kafka.
	dispatcher := outbox.NewDispatcher(db.DB, kafkaBroker, kafkaTopic, dlqTopic, maxRetries)
	go dispatcher.Start(ctx)

	go func() {
		<-ctx.Done()
		log.Println("🛑 Shutdown signal received, stopping gRPC server")
		grpcServer.GracefulStop()
	}()

	log.Printf("🚀 Payment Service (gRPC) listening on :%s", port)
	if err := grpcServer.Serve(lis); err != nil {
		if ctx.Err() == nil {
			log.Fatalf("❌ gRPC server failed: %v", err)
		}
		log.Println("Payment service stopped")
	}
}

func getEnv(key, defaultVal string) string {
	if val := os.Getenv(key); val != "" {
		return val
	}
	return defaultVal
}

func getEnvAsInt(key string, defaultVal int) int {
	val := os.Getenv(key)
	if val == "" {
		return defaultVal
	}

	parsed, err := strconv.Atoi(val)
	if err != nil || parsed <= 0 {
		return defaultVal
	}

	return parsed
}

// RegisterPaymentServiceServer is what would be generated by protoc.
// We define it here manually since we're not running protoc in this example.
func init() {
	// This wires up the proto registration.
	// In a real project, protoc generates this automatically.
}
